Update reproduce.yml

diff --git a/.github/workflows/reproduce.yml b/.github/workflows/reproduce.yml
--- a/.github/workflows/reproduce.yml
+++ b/.github/workflows/reproduce.yml
@@ -12,12 +12,12 @@ jobs:
         uses: actions/setup-java@v2
         with:
           distribution: 'adopt'
-          java-version: '11'
+          java-version: '20'
   
       - name: Checkout to specific commit
         run: |
           git fsck  
-          #git checkout 8d96ed9 || echo "Checkout failed"  
+          #git checkout 8d96ed95ffcbd8fc0596e1294822777c28ff0bc8 || echo "Checkout failed"  
           
       - name: Compile Module
         run: mvn test-compile -pl ignite-3 -am
